version: '3.8'
services:
  trello-api: 
    build: .
    container_name: trello-api
    working_dir: /backend/app
    restart: always
    volumes:
      - .:/src/app
    environment:
      - LOCAL_DEV_APP_PORT=8017
      - NODE_ENV=development
      - MONGO_URI=${MONGODB_URI}
    ports:
      - "8017:8017"
    networks:
      - app-network
networks:
  app-network:
    external: true